[font]
size = 14.8
normal.family = "PragmataPro"

[window]
option_as_alt = "OnlyLeft"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "м"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "с"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "т"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "ц"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "а"
mods = "Command"
action = "SearchForward"

# Colors (Solarized Light)

# Default colors
[colors.primary]
background = '#fdf6e3'
foreground = '#586e75'

# Normal colors
[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

# Bright colors
[colors.bright]
black   = '#002b36'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'
